export const dummyProd = [
    {
      id: 1,
      prod_catID: 12,
      prod_active: "Yes",
      prod_name: "T Shirt",
      prod_description: "",
      prod_image: "",
      prod_type: [{id: 1, value: 'Summer'}],
      prod_sequence: 2,
      prod_filterList: [{id : 2, value: 'New'}]
    },
    {
      id: 2,
      prod_catID: 23,
      prod_active: "No",
      prod_name: "Pant",
      prod_description: "",
      prod_image: "",
      prod_type: [{id: 1, value: 'Summer'}],
      prod_sequence: 2,
      prod_filterList: [{id : 2, value: 'New'}]
    },
    {
      id: 3,
      prod_catID: 45,
      prod_active: "No",
      prod_name: "Boxer",
      prod_description: "",
      prod_image: "",
      prod_type: [{id: 1, value: 'Summer'}],
      prod_sequence: 2,
      prod_filterList: [{id : 2, value: 'New'}]
    },
    {
      id: 4,
      prod_catID: 22,
      prod_active: "Yes",
      prod_name: "Shirt",
      prod_description: "",
      prod_image: "",
      prod_type: [{id: 1, value: 'Summer'}],
      prod_sequence: 2,
      prod_filterList: [{id : 2, value: 'New'}]
    },
    {
      id: 5,
      prod_catID: 54,
      prod_active: "No",
      prod_name: "Shorts",
      prod_description: "",
      prod_image: "",
      prod_type: [{id: 1, value: 'Summer'}],
      prod_sequence: 2,
      prod_filterList: [{id : 2, value: 'New'}]
    },
    {
      id: 6,
      prod_catID: 24,
      prod_active: "No",
      prod_name: "Cargo",
      prod_description: "",
      prod_image: "",
      prod_type: [{id: 1, value: 'Summer'}],
      prod_sequence: 2,
      prod_filterList: [{id : 2, value: 'New'}]
    },
    {
      id: 7,
      prod_catID: 11,
      prod_active: "Yes",
      prod_name: "Jeans",
      prod_description: "",
      prod_image: "",
      prod_type: [{id: 1, value: 'Summer'}],
      prod_sequence: 1,
      prod_filterList: [{id : 2, value: 'New'}],
    },
    {
      id: 8,
      prod_catID: 9,
      prod_active: "Yes",
      prod_name: "Hoodie",
      prod_description: "",
      prod_image: "",
      prod_type: [{id: 1, value: 'Summer'}],
      prod_sequence: 1,
      prod_filterList: [{id : 2, value: 'New'}],
    },
    {
      id: 9,
      prod_catID: 7,
      prod_active: "Yes",
      prod_name: "Jersey",
      prod_description: "",
      prod_image: "",
      prod_type: [{id: 1, value: 'Summer'}],
      prod_sequence: 1,
      prod_filterList: [{id : 2, value: 'New'}],
    },
  ];