export const dummyProd = [
  /*
  {
    cat_id: 1,
    category: "men",
    products: [
      {
        id: 1,
        prod_catID: 12,
        prod_active: "Yes",
        prod_name: "T Shirt",
        prod_description: "",
        prod_image: "",
        prod_type: [{ id: 1, value: "Summer" }],
        prod_sequence: 2,
        prod_filterList: [{ id: 2, value: "New" }],
        subProducts: [
          {
            id: 1,
            prod_id: 12,
            SubProd_FilterValues: "Value 1",
            SubProd_name: "Red shirt ",
            SubProd_active: "Active",
            SubProd_Filter: "Filter 1",
          },
        ],
      },
      {
        id: 2,
        prod_catID: 23,
        prod_active: "No",
        prod_name: "Pant",
        prod_description: "",
        prod_image: "",
        prod_type: [{ id: 1, value: "Summer" }],
        prod_sequence: 2,
        prod_filterList: [{ id: 2, value: "New" }],
        subProducts: [
          {
            id: 1,
            prod_id: 12,
            SubProd_FilterValues: "Value 1",
            SubProd_name: "Red Pant ",
            SubProd_active: "Active",
            SubProd_Filter: "Filter 1",
          },
        ],
      },
    ],
  },
*/
  // {
  //   id: 3,
  //   prod_catID: 45,
  //   prod_active: "No",
  //   prod_name: "Boxer",
  //   prod_description: "",
  //   prod_image: "",
  //   prod_type: [{id: 1, value: 'Summer'}],
  //   prod_sequence: 2,
  //   prod_filterList: [{id : 2, value: 'New'}]
  // },
  // {
  //   id: 4,
  //   prod_catID: 22,
  //   prod_active: "Yes",
  //   prod_name: "Shirt",
  //   prod_description: "",
  //   prod_image: "",
  //   prod_type: [{id: 1, value: 'Summer'}],
  //   prod_sequence: 2,
  //   prod_filterList: [{id : 2, value: 'New'}]
  // },
  // {
  //   id: 5,
  //   prod_catID: 54,
  //   prod_active: "No",
  //   prod_name: "Shorts",
  //   prod_description: "",
  //   prod_image: "",
  //   prod_type: [{id: 1, value: 'Summer'}],
  //   prod_sequence: 2,
  //   prod_filterList: [{id : 2, value: 'New'}]
  // },
  // {
  //   id: 6,
  //   prod_catID: 24,
  //   prod_active: "No",
  //   prod_name: "Cargo",
  //   prod_description: "",
  //   prod_image: "",
  //   prod_type: [{id: 1, value: 'Summer'}],
  //   prod_sequence: 2,
  //   prod_filterList: [{id : 2, value: 'New'}]
  // },
  // {
  //   id: 7,
  //   prod_catID: 11,
  //   prod_active: "Yes",
  //   prod_name: "Jeans",
  //   prod_description: "",
  //   prod_image: "",
  //   prod_type: [{id: 1, value: 'Summer'}],
  //   prod_sequence: 1,
  //   prod_filterList: [{id : 2, value: 'New'}],
  // },
  // {
  //   id: 8,
  //   prod_catID: 9,
  //   prod_active: "Yes",
  //   prod_name: "Hoodie",
  //   prod_description: "",
  //   prod_image: "",
  //   prod_type: [{id: 1, value: 'Summer'}],
  //   prod_sequence: 1,
  //   prod_filterList: [{id : 2, value: 'New'}],
  // },
  // {
  //   id: 9,
  //   prod_catID: 7,
  //   prod_active: "Yes",
  //   prod_name: "Jersey",
  //   prod_description: "",
  //   prod_image: "",
  //   prod_type: [{id: 1, value: 'Summer'}],
  //   prod_sequence: 1,
  //   prod_filterList: [{id : 2, value: 'New'}],
  // },

  {
    id: 0,
    prod_catID: 1,
    prod_active: "Active",
    prod_name: "Product 1",
    prod_description: "Description 1",
    prod_image: "image1.jpg",
    prod_type: [
      { id: 1, value: "Type A" },
      { id: 2, value: "Type B" },
    ],
    prod_sequence: 1,
    prod_filterList: [
      { id: 1, value: "Filter A" },
      { id: 2, value: "Filter B" },
    ],
  },
  {
    id: 1,
    prod_catID: 1,
    prod_active: "Active",
    prod_name: "Product 1",
    prod_description: "Description 1",
    prod_image: "image1.jpg",
    prod_type: [
      { id: 1, value: "Type A" },
      { id: 2, value: "Type B" },
    ],
    prod_sequence: 1,
    prod_filterList: [
      { id: 1, value: "Filter A" },
      { id: 2, value: "Filter B" },
    ],
  },

  {
    id: 2,
    prod_catID: 1,
    prod_active: "Active",
    prod_name: "Product 2",
    prod_description: "Description 2",
    prod_image: "image2.jpg",
    prod_type: [{ id: 1, value: "Type A" }],
    prod_sequence: 2,
    prod_filterList: [{ id: 1, value: "Filter A" }],
  },
  {
    id: 3,
    prod_catID: 2,
    prod_active: "Inactive",
    prod_name: "Product 3",
    prod_description: "Description 3",
    prod_image: "image3.jpg",
    prod_type: [{ id: 1, value: "Type B" }],
    prod_sequence: 3,
    prod_filterList: [{ id: 2, value: "Filter B" }],
  },
  {
    id: 4,
    prod_catID: 2,
    prod_active: "Active",
    prod_name: "Product 4",
    prod_description: "Description 4",
    prod_image: "image4.jpg",
    prod_type: [{ id: 2, value: "Type B" }],
    prod_sequence: 4,
    prod_filterList: [{ id: 2, value: "Filter B" }],
  },
  {
    id: 5,
    prod_catID: 3,
    prod_active: "Active",
    prod_name: "Product 5",
    prod_description: "Description 5",
    prod_image: "image5.jpg",
    prod_type: [
      { id: 1, value: "Type A" },
      { id: 2, value: "Type B" },
    ],
    prod_sequence: 5,
    prod_filterList: [
      { id: 1, value: "Filter A" },
      { id: 2, value: "Filter B" },
    ],
  },
  {
    id: 6,
    prod_catID: 1,
    prod_active: "Active",
    prod_name: "Product 1",
    prod_description: "Description 1",
    prod_image: "image1.jpg",
    prod_type: [
      { id: 1, value: "Type A" },
      { id: 2, value: "Type B" },
    ],
    prod_sequence: 1,
    prod_filterList: [
      { id: 1, value: "Filter A" },
      { id: 2, value: "Filter B" },
    ],
  },
];
