export const dummyItem = [
  {
    id: 1,
    item_subProd: 12,
    item_active: "Yes",
    item_sku: "T Shirt",
    item_description: "",
    item_image: "",
    item_type: [{ id: 1, value: "Summer" }],
    item_sequence: 2,
    item_filterList: [{ id: 2, value: "New" }],
  },
  {
    id: 2,
    item_subProd: 23,
    item_active: "No",
    item_sku: "Pant",
    item_description: "",
    item_image: "",
    item_type: [{ id: 1, value: "Summer" }],
    item_sequence: 2,
    item_filterList: [{ id: 2, value: "New" }],
  },
  {
    id: 3,
    item_subProd: 45,
    item_active: "No",
    item_sku: "Boxer",
    item_description: "",
    item_image: "",
    item_type: [{ id: 1, value: "Summer" }],
    item_sequence: 2,
    item_filterList: [{ id: 2, value: "New" }],
  },
  {
    id: 4,
    item_subProd: 22,
    item_active: "Yes",
    item_sku: "Shirt",
    item_description: "",
    item_image: "",
    item_type: [{ id: 1, value: "Summer" }],
    item_sequence: 2,
    item_filterList: [{ id: 2, value: "New" }],
  },
  {
    id: 5,
    item_subProd: 54,
    item_active: "No",
    item_sku: "Shorts",
    item_description: "",
    item_image: "",
    item_type: [{ id: 1, value: "Summer" }],
    item_sequence: 2,
    item_filterList: [{ id: 2, value: "New" }],
  },
  {
    id: 6,
    item_subProd: 24,
    item_active: "No",
    item_sku: "Cargo",
    item_description: "",
    item_image: "",
    item_type: [{ id: 1, value: "Summer" }],
    item_sequence: 2,
    item_filterList: [{ id: 2, value: "New" }],
  },
  {
    id: 7,
    item_subProd: 11,
    item_active: "Yes",
    item_sku: "Jeans",
    item_description: "",
    item_image: "",
    item_type: [{ id: 1, value: "Summer" }],
    item_sequence: 1,
    item_filterList: [{ id: 2, value: "New" }],
  },
  {
    id: 8,
    item_subProd: 9,
    item_active: "Yes",
    item_sku: "Hoodie",
    item_description: "",
    item_image: "",
    item_type: [{ id: 1, value: "Summer" }],
    item_sequence: 1,
    item_filterList: [{ id: 2, value: "New" }],
  },
  {
    id: 9,
    item_subProd: 7,
    item_active: "Yes",
    item_sku: "Jersey",
    item_description: "",
    item_image: "",
    item_type: [{ id: 1, value: "Summer" }],
    item_sequence: 1,
    item_filterList: [{ id: 2, value: "New" }],
  },
];
